// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3u3MnGSaBN5xWuVbsxgpLkgD5imnmWrw',
    appId: '1:636535752196:web:437b886bbb0f6ae868d751',
    messagingSenderId: '636535752196',
    projectId: 'financy-app-ee3e7',
    authDomain: 'financy-app-ee3e7.firebaseapp.com',
    storageBucket: 'financy-app-ee3e7.firebasestorage.app',
    measurementId: 'G-69G191EZB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwNhzaLF2bwFSszJVbnxB1o6S2eicpd30',
    appId: '1:636535752196:android:2c17eebe1d098bb868d751',
    messagingSenderId: '636535752196',
    projectId: 'financy-app-ee3e7',
    storageBucket: 'financy-app-ee3e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPA2HeN2bB0uYNfJpsxNfbfpSu-s5qqk',
    appId: '1:636535752196:ios:d81bf932a0f13a9c68d751',
    messagingSenderId: '636535752196',
    projectId: 'financy-app-ee3e7',
    storageBucket: 'financy-app-ee3e7.firebasestorage.app',
    iosBundleId: 'com.thanlar.financy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPA2HeN2bB0uYNfJpsxNfbfpSu-s5qqk',
    appId: '1:636535752196:ios:d81bf932a0f13a9c68d751',
    messagingSenderId: '636535752196',
    projectId: 'financy-app-ee3e7',
    storageBucket: 'financy-app-ee3e7.firebasestorage.app',
    iosBundleId: 'com.thanlar.financy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3u3MnGSaBN5xWuVbsxgpLkgD5imnmWrw',
    appId: '1:636535752196:web:53270391f261d86e68d751',
    messagingSenderId: '636535752196',
    projectId: 'financy-app-ee3e7',
    authDomain: 'financy-app-ee3e7.firebaseapp.com',
    storageBucket: 'financy-app-ee3e7.firebasestorage.app',
    measurementId: 'G-9SN5ZHLE8J',
  );
}
